### ISSUE TITLE
Top NavBar Bug

### ISSUE THREAD

**Issue by Kharg** [dubas-pro/ext-light-theme#12]
Top Navbar isn't behaving correctly, it messes up the CRM.
Using Espo 7.3.3 and Dubas Light 1.1.0
![image](https://user-images.githubusercontent.com/32223252/223856330-c7e210b8-d90b-4528-a0bc-c3b32aeb6793.png)

**Comment by emillod** [comment]
Thanks for creating issue. Will check asap.

**Comment by emillod** [comment]
Hello, have you checked the newest version? :) 
It's working for sure with the newest version. I'm resolving this issue for now.
